config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions do
    put 'hide', on: :member
  end
  resource :session, only: %i[new create destroy]
  resources :users, param: :nickname, except: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  validates :body, presence: true, length: { maximum: 280 }

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_validation :downcase_nickname

  has_many :questions, dependent: :delete_all
  has_many :authored_questions, class_name: 'Question', foreign_key: 'author_id', dependent: :nullify

  validates :email, :nickname, presence: true, uniqueness: true
  validates :email, format: {
    with: /\A[a-z\d_+.\-]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/
  }
  validates :nickname, length: { in: 2..40 }, format: { with: /\A\w+\z/ }

  def to_param
    nickname
  end

  private

  def downcase_nickname
    nickname.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def redirect_with_alert
    redirect_to root_path, alert: 'You shall not pass!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_current_user, only: [:edit, :destroy, :hide, :update]
  before_action :set_question_for_current_user, only: [:edit, :destroy, :hide, :update]

  def create
    question_params = params.require(:question).permit(:body, :user_id, :author)

    @question = Question.new(question_params)

    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user), notice: 'Your question has been created.'
    else
      flash.now[:alert] = 'Input data is invalid.'
      render :new
    end
  end

  def destroy
    @user = @question.user
    @question.destroy

    redirect_to user_path(@user), notice: 'Your question has been deleted.'
  end

  def edit
  end

  def hide
    @question.update(hidden: true)

    redirect_to question_path(@question), notice: 'Your question is hidden now.'
  end

  def index
    @questions = Question.order(created_at: :desc).first(10)
    @users = User.order(created_at: :desc).first(10)
  end

  def new
    @user = User.find(params[:user_id])
    @question = Question.new(user: @user)
  end

  def show
    @question = Question.find(params[:id])
  end

  def update
    question_params = params.require(:question).permit(:body, :answer)

    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Your question has been updated.'
    else
      flash.now[:alert] = 'Input data is invalid.'
      render :edit
    end
  end

  private

  def ensure_current_user
    redirect_with_alert unless current_user.present?
  end

  def set_question_for_current_user
    @question = current_user.questions.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user_params = params.require(:session)

    user = User.find_by(email: user_params[:email])&.authenticate(user_params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: 'You signed in'
    else
      flash[:alert] = 'Wrong email and/or password'

      render :new
    end
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'You signed out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:destroy, :edit, :show, :update]
  before_action :authorize_user, only: [:edit, :update, :destroy]


  def new
    session[:current_time] = Time.now

    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'You have signed up successfully.'
    else
      flash.now[:alert] = 'The input data is invalid.'
      render :new
    end
  end

  def destroy
    @user.destroy
    session.delete(:user_id)

    redirect_to root_path, notice: 'Your account has been deleted.'
  end

  def edit
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @question = Question.new(user: @user)
  end

  def update
    if @user.update(user_params)
      redirect_to user_path, notice: 'Your profile has been updated.'
    else
      flash.now[:alert] = 'The input data is invalid.'
      render :edit
    end
  end

  private

  def authorize_user
    redirect_with_alert unless @user == current_user
  end

  def user_params
    params.require(:user).permit(
      :name, :nickname, :email, :password, :password_confirmation, :navbar_color
    )
  end

  def set_user
    @user = User.find_by!(nickname: params[:nickname])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inclination(count, one, many)
    return one if count == 1
    many
  end

  def question_author(question)
    return link_to display_at_sign(question.author), user_path(question.author) if question.author
    'anonymous user'
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def display_at_sign(user)
    "@#{user.nickname}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ask.me</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="wrapper">
      <div class="navbar" style="
        background-color: <% if current_user.present? && current_user.navbar_color %>
          <%= current_user.navbar_color %>
        <% else %>
          <%= '#370617' %>
        <% end %>">
        <p class="title-sm text-bold"><%= link_to 'ask.me', root_path %></p>
        <div>
          <% if current_user.present? %>
            <%= link_to display_at_sign(current_user), user_path(current_user) %>
            <%= button_to 'Sign out', session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign up', new_user_path, class: 'button button-yellow' %>
            <%= link_to 'Sign in', new_session_path, class: 'button button-yellow' %>
          <% end %>
        </div>
      </div>

      <% if flash[:notice].present? %>
        <p class="mt mb message message-notice"><%= flash[:notice] %></p>
      <% elsif flash[:alert].present? %>
        <p class="mt mb message message-alert"><%= flash[:alert] %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<% if question.errors.any? %>
  <div class="mt">
    <% question.errors.full_messages.each do |message| %>
      <p class="mb-sm text-red"><%= message %></p>
    <% end %>
  </div>
<% end %>

<%= form_with model: question, data: { turbo: false } do |form| %>
  <%= form.hidden_field :user_id %>

  <p><%= form.label :body, 'Question text' %></p>
  <p><%= form.text_area :body, rows: 5, class: 'form-text-area' %></p>

  <% if question.persisted? %>
    <p><%= form.label :answer, 'Answer' %></p>
    <p><%= form.text_area :answer, rows: 5, class: 'form-text-area' %></p>
  <% end %>

  <p class="mt"><%= form.submit 'Save', class: 'button button-main' %>
    or <%= link_to 'return', :back %></p>
<% end %>

app/views/questions/_question.html.erb
<p class="text-sm text-grey mb">
  <%= question_author(question) %>`s
  question <%= link_to "##{question.id}", question_path(question) %>
  for <%= link_to display_at_sign(question.user), user_path(question.user) %>
</p>

<div class="mb-sm line-break"><%= question.body %></div>

<% if question.answer.present? %>
  <div class="text-dark-red mb-sm">
    <%= question.answer %>
  </div>
<% end %>

<div class="text-sm question-footer">
  <div class="text-grey">
    <%= l(question.created_at, format: :short) %>
  </div>

  <div>
    <% if question.user == current_user %>
      <% edit_icon = (question.answer.present? ? 'pencil' : 'reply') %>
      <%= link_to fa_icon(edit_icon), edit_question_path(question), title: 'Edit question' %>
      <%= button_to fa_icon('trash-o'), question_path(question), method: :delete,
                    title: 'Delete question', form: { data: { turbo_confirm: 'Are you sure?' } } %>
      <% unless question.hidden %>
        <%= button_to fa_icon('eye-slash'), hide_question_path(question), title: 'Hide question',
                      method: :put %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/questions/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Edit question <%= @question.id %></h2>

  <%= render 'form', question: @question %>
</div>

app/views/questions/index.html.erb
<div class="container">
  <h2 class="title-lg mb">Recently joined us</h2>

  <div class="users-box">
    <% @users.each do |user| %>
      <%= render partial: 'users/user_avatar', locals: { user: user } %>
    <% end %>
  </div>
</div>

<div>
  <h2 class="container title-lg mt">
    Last <%= @questions.count %>
    <%= inclination(@questions.count, 'question', 'questions') %>
  </h2>
  <% @questions.each do |question| %>
    <div class="container mt-sm <%= "text-hidden" if question.hidden %>">

      <%= render question %>
    </div>
  <% end %>
</div>

app/views/questions/new.html.erb
<div class="container">
  <h2 class="title-lg mb-sm">New question</h2>
  <p class="mb">for <%= link_to display_at_sign(@user), user_path(@user) %></p>

  <%= render 'form', question: @question %>
</div>

app/views/questions/show.html.erb
<div class="container">
  <h2 class="title-lg mb">Question <%= @question.id %></h2>

  <p class="mt">
    <%= link_to 'All questions', user_path(@question.user), class: 'button button-main' %>
    for <%= link_to display_at_sign(@question.user), user_path(@question.user) %>
  </p>
</div>

<div class="container mt">
  <%= render 'question', question: @question %>
</div>

app/views/users/_user_avatar.html.erb
<% background_class = "user-bg-color#{user.id % 5}" %>
<% nickname_letter = user.nickname.first.upcase %>

<div class="users-box-user <%= background_class %> rounded mr ml">
  <a href="<%= user_path(user) %>">
    <h1 class="title-lg text-bold"><%= nickname_letter %></h1>
  </a>
</div>

app/views/users/edit.html.erb
<div class="container">
  <h2 class="title-lg mb">Edit your profile</h2>

  <% if @user.errors.any? %>
    <div class="mt">
      <% @user.errors.full_messages.each do |message| %>
        <p class="mb-sm text-red"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%= form_with model: @user, data: { turbo: false } do |form| %>
    <p><%= form.label :name, 'Your name' %></p>
    <p><%= form.text_field :name, class: 'form-text-field' %></p>

    <p class="mt"><%= form.label :nickname, 'Your nickname' %></p>
    <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

    <p class="mt text-sm">If you don't want to change your password, just leave
      next fields empty.</p>

    <p class="mt"><%= form.label :password %></p>
    <p><%= form.password_field :password, class: 'form-text-field' %></p>

    <p class="mt"><%= form.label :password_confirmation %></p>
    <p><%= form.password_field :password_confirmation, class: 'form-text-field' %></p>

    <p class="mt"><%= form.label :navbar_color, 'You can also change the header`s color' %></p>
    <p><%= form.color_field :navbar_color, class: 'color-field', id: 'color_field' %></p>

    <button type="button" onclick="changeColor()">choose default color</button>

    <p class="mt-lg"><%= form.submit 'Save', class: 'button button-main' %></p>
  <% end %>

  <p class="mt-lg"><%= button_to 'Delete the account', user_path(@user), method: :delete,
  form: { data: { turbo_confirm: 'Are you sure?' } } %></p>
</div>

<script>
  function changeColor() {
    document.getElementById("color_field").value = "#370617";
  }
</script>

app/views/users/new.html.erb
<div class="container">
  <h2 class="title-lg mb">Join us and ask your questions</h2>

  <%= form_with model: @user do |form| %>
  <p><%= form.label :name, 'Your name' %></p>
  <p><%= form.text_field :name, class: 'form-text-field' %></p>

  <p class="mt"><%= form.label :nickname, 'Your nickname' %></p>
  <p><%= form.text_field :nickname, class: 'form-text-field' %></p>

  <p class="mt"><%= form.label :email %></p>
  <p><%= form.text_field :email, class: 'form-text-field' %></p>

  <p class="mt"><%= form.label :password %></p>
  <p><%= form.password_field :password, class: 'form-text-field' %></p>

  <p class="mt-lg"><%= form.submit 'Sign up', class: 'button button-main' %></p>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container user-box">
  <h2 class="title-lg mt mb-sm"><%= @user.name %></h2>
  <% if @user == current_user %>
    <%= link_to fa_icon('pencil'), edit_user_path(@user), class: 'mb-sm button' %>
  <% end %>
  <h3 class="text-bold mb-lg"><%= display_at_sign(@user) %></h3>
</div>

<div class="container">
  <%= link_to 'Ask', new_question_path(user_id: @user.id),
                class: 'button button-yellow mb' %>
  <%= render 'questions/form', question: @question %>
</div>

<div>
  <h2 class="container title-lg mt-sm">
    <% if @questions.present? || current_user == @user %>
      <%= @questions.count %> <%= inclination(@questions.count, 'question', 'questions') %>
    <% else %>
      <p>Ask <%= display_at_sign(@user) %> something!</p>
    <% end %>
  </h2>
  <% @questions.each do |question| %>
    <div class="container mt-sm <%= "text-hidden" if question.hidden %>">
      <%= render question %>
    </div>
  <% end %>
</div>